apiVersion: apps/v1
kind: Deployment
metadata:
  name: fps-game-7379
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fps-game-7379
  template:
    spec:
      containers:
      - name: fps-game-7379
        image: ahve/fps-game-7379:latest
        ports:
        - containerPort: 5000
